### ISSUE TITLE
Writing does nothing after init.

### ISSUE THREAD

**Issue by kevinalavik** [Mintsuki/Flanterm#14]
So i can confirm it initialized successfully since i see a cursor and the ctx isnt null. I also can confirm that the framebuffer is fine. And i can even disable the cursor then full_refresh and it works tho when i try to write i see nothing just this (the cursor):
![image](https://github.com/user-attachments/assets/5e00aaa3-a96a-4bfc-8c3b-c2e7d1ad0f01)

Here is my code: 
```cpp
struct flanterm_context *ft_ctx = flanterm_fb_init(NULL, NULL, data->framebuffer->address, data->framebuffer->width, data->framebuffer->height, data->framebuffer->pitch, data->framebuffer->red_mask_size, data->framebuffer->red_mask_shift, data->framebuffer->green_mask_size, data->framebuffer->green_mask_shift, data->framebuffer->blue_mask_size, data->framebuffer->blue_mask_shift, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 0, 0);
if(ft_ctx == NULL) {
    outb(0xE9, 'E');
    hlt();
}

const char msg[] = "Hello world\n";
flanterm_write(ft_ctx, msg, sizeof(msg));
```

**Comment by kevinalavik** [comment]
This could also be some kind of bootloader issue. But im 99% sure its not since the framebuffer seems fine here is the bootloader framebuffer code: https://github.com/sphynxos/sphynxboot/blob/v1.x.x-alpha/common/src/boot/framebuffer.c

**Comment by kevinalavik** [comment]
I also tried it in C++ but that didnt work: https://github.com/sphynxos/sphynx/blob/0c01cdb346657bf3359f2e331a2dd745a579e3cc/kernel/src/kernel.cpp#L40

**Comment by Mintsuki** [comment]
Make sure that you have mem*() functions and that they work correctly and are standard compliant.

**Comment by kevinalavik** [comment]
> Make sure that you have mem*() functions and that they work correctly and are standard compliant.

@mintsuki These aree my current once (from the C++ test):
```cpp
extern "C" void* memset(void* d, int c, size_t n) {
    auto* p = static_cast<char*>(d);
    while (n--) {
        *p++ = c;
    }
    return d;
}

extern "C" void* memcpy(void* dest, const void* src, size_t n) {
    auto* p1 = static_cast<char*>(dest);
    auto* p2 = static_cast<const char*>(src);
    while (n--) {
        *p1++ = *p2++;
    }
    return dest;
}
``` 

and afaik they work and are standard compliant. Thanks for the fast reply

**Comment by kevinalavik** [comment]
Also @mintsuki i jnow see i made the issue in the wrong repo. Oops well anyways i still use ur repo in my code and the issue isnt resolved

**Comment by kevinalavik** [comment]
> Also @mintsuki i jnow see i made the issue in the wrong repo. Oops well anyways i still use ur repo in my code and the issue isnt resolved

ohhh nvm i got confusd with the new owner sorry :^)

**Comment by Mintsuki** [comment]
you've been unbanned from the osdev discord (as a matter of fact, everyone has), so i invite you to ask over there instead as it may be easier

**Comment by kevinalavik** [comment]
> you've been unbanned from the osdev discord (as a matter of fact, everyone has), so i invite you to ask over there instead as it may be easier

@mintsuki oh lovley! Ill make sure to behave cya

**Comment by kevinalavik** [comment]
The issue was an issue with strings and it was my ELF loaders fault. Thanks to qookie that pointed out the mistake in my ELF loader, anyways now it works.
